/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const EllAside: typeof import('@my-element-plus/components')['EllAside']
  const EllFooter: typeof import('@my-element-plus/components')['EllFooter']
  const EllHeader: typeof import('@my-element-plus/components')['EllHeader']
  const EllMain: typeof import('@my-element-plus/components')['EllMain']
}
