/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EllAside: typeof import('@my-element-plus/components')['EllAside']
    EllButton: typeof import('@my-element-plus/components')['EllButton']
    EllContainer: typeof import('@my-element-plus/components')['EllContainer']
    EllFooter: typeof import('@my-element-plus/components')['EllFooter']
    EllHeader: typeof import('@my-element-plus/components')['EllHeader']
    EllMain: typeof import('@my-element-plus/components')['EllMain']
  }
}
