/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    EllAside: typeof import('@my-element-plus/components')['EllAside']
    EllButton: typeof import('@my-element-plus/components')['EllButton']
    EllButtonGroup: typeof import('@my-element-plus/components')['EllButtonGroup']
    EllContainer: typeof import('@my-element-plus/components')['EllContainer']
    EllFooter: typeof import('@my-element-plus/components')['EllFooter']
    EllHeader: typeof import('@my-element-plus/components')['EllHeader']
    EllInputNumber: typeof import('@my-element-plus/components')['EllInputNumber']
    EllMain: typeof import('@my-element-plus/components')['EllMain']
    EllRadio: typeof import('@my-element-plus/components')['EllRadio']
    EllRadioButton: typeof import('@my-element-plus/components')['EllRadioButton']
    EllRadioGroup: typeof import('@my-element-plus/components')['EllRadioGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  }
}
